#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/.aliases

export EDITOR=vim
export VISUAL=$EDITOR

if [[ -e /usr/share/terminfo/x/xterm+256color ]] && [[ "$COLORTERM" == "xfce4-terminal" ]]; then
    export TERM=xterm-256color
fi

fpath=(
    ~/.completions
    ~/.zfuncs
    "${fpath[@]}"
)
compinit

autoload -Uz fbr copy-buffer colors

eval "$(pyenv init -)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
